name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/ethlogo.png
    - assets/page-1/images/profile.png
    - assets/page-1/images/logo.png
    - assets/page-1/images/home.png
    - assets/page-1/images/cretorimage.png
    - assets/page-1/images/historylogo.png
    - assets/page-1/images/logo-p3X.png
    - assets/page-1/images/nft4image.png
    - assets/page-1/images/nftimage.png
    - assets/page-1/images/profile-qx1.png
    - assets/page-1/images/purchaselogo.png
    - assets/page-1/images/selcuk-1.png
    - assets/page-1/images/btclogo2.png
    - assets/page-1/images/salelogo.png
    - assets/page-1/images/profile-fKj.png
    - assets/page-1/images/logo-cER.png
    - assets/page-1/images/googlelogo.png
    - assets/page-1/images/creatorbtcinfo.png
    - assets/page-1/images/logo-CkD.png
    - assets/page-1/images/logo-bj3.png
    - assets/page-1/images/nft1infoimage.png
    - assets/page-1/images/home-fJV.png
    - assets/page-1/images/nft2image.png
    - assets/page-1/images/nft3infoimage.png
    - assets/page-1/images/btclogo.png
    - assets/page-1/images/btclogo2-A4D.png
    - assets/page-1/images/nft3image.png
    - assets/page-1/images/nftimage-RF3.png
    - assets/page-1/images/btclogo2-MPb.png
    - assets/page-1/images/btclogo2-gAy.png
    - assets/page-1/images/home-1U9.png
    - assets/page-1/images/creatorbtcinfo-8Ym.png
    - assets/page-1/images/nft1infoimage-RGH.png
    - assets/page-1/images/home-X4R.png
    - assets/page-1/images/saleback-bg.png
    - assets/page-1/images/cart.png
    - assets/page-1/images/btcc2.png
    - assets/page-1/images/creatorimage.png
    - assets/page-1/images/home-JUV.png
    - assets/page-1/images/btclogo-Rp1.png
    - assets/page-1/images/rightlogo.png
    - assets/page-1/images/nft1image.png
    - assets/page-1/images/polygon-1.png
    - assets/page-1/images/profile-jNM.png
    - assets/page-1/images/userimage.png
    - assets/page-1/images/btcc1.png
    - assets/page-1/images/profile-dbj.png
    - assets/page-1/images/rightlogo-Yyb.png
    - assets/page-1/images/casual-life-3d-yellow-bitcoin-1-2.png
    - assets/page-1/images/hidelogo.png
    - assets/page-1/images/creatorbtcinfo-xXX.png
    - assets/page-1/images/ethlogo3.png
    - assets/page-1/images/btclogo-GHK.png
    - assets/page-1/images/btcc3.png
    - assets/page-1/images/home-jAu.png
    - assets/page-1/images/casual-life-3d-yellow-bitcoin-1-2-3Bb.png
    - assets/page-1/images/walletlogo.png
    - assets/page-1/images/btclogo-w25.png
    - assets/page-1/images/nft4infoimage.png
    - assets/page-1/images/cart-dvV.png
    - assets/page-1/images/iphonecardlogo.png
    - assets/page-1/images/girllogo.png
    - assets/page-1/images/d-casual-life-ethereum-2.png
    - assets/page-1/images/hidelogo-g85.png
    - assets/page-1/images/nft2infoimage.png
    - assets/page-1/images/agentlogo.png
    - assets/page-1/images/home-MED.png
    - assets/page-1/images/casual-life-3d-yellow-bitcoin-1-2-W2Z.png
    - assets/page-1/images/cart-p3F.png
    - assets/page-1/images/met-1.png
    - assets/page-1/images/cart-t37.png
    - assets/page-1/images/iphonelogo.png
    - assets/page-1/images/logo-YdT.png
    - assets/page-1/images/cart-UGD.png
    - assets/page-1/images/btclogo3.png
    - assets/page-1/images/nftimage-YWy.png
    - assets/page-1/images/btcc4.png
    - assets/page-1/images/cart-K57.png
    - assets/page-1/images/cart-ig5.png
    - assets/page-1/images/nft2infoimage-dHF.png
    - assets/page-1/images/deskmanlogo.png
    - assets/page-1/images/right.png
    - assets/page-1/images/profile-6gd.png
    - assets/page-1/images/logo-3Ly.png
    - assets/page-1/images/ethlogo-nJZ.png
    - assets/page-1/images/cretorbtcinfo.png
    - assets/page-1/images/profile-wqf.png
    - assets/page-1/images/flyingman.png
    - assets/page-1/images/nftimage-v37.png
    - assets/page-1/images/ellipse-2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
